version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka-cluster:
    image: wurstmeister/kafka:0.9.0.1-1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.19.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_BROKER_ID: 999 # not specifying a broker ID will allow cluster to scale out (use --no-recreate)
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  connect:
    build: .
    ports:
      - "8086:8086" # Connect REST API
    volumes:
      - "./data-sources:/opt/data-sources"
    depends_on:
      - kafka-cluster
  connect-ui:
    image: landoop/kafka-connect-ui:latest
    environment:
      CONNECT_URL: "connect:8086"
    ports:
      - "8000:8000"
    depends_on:
      - connect
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.port=9200"
      - "http.cors.allow-origin=*"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    ports:
      - "9200:9200"
    depends_on:
      - kafka-cluster
    volumes:
      - esdata:/usr/share/elasticsearch/data
  elasticsearch-ui:
    image: appbaseio/dejavu
    ports:
      - "1358:1358"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local